
store_path: /home/csewell/Documents/aiida-core/test_repo/

su_db_username: chrisjsewell
# su_db_password:  # not yet supported

db_engine: postgresql_psycopg2
db_backend: django

db_host: localhost
db_port: 5432
db_name: basic_db
db_username: chrisjsewell
db_password: niceday

profile: basic
email: christopher.sewell@epfl.ch
first_name: Chris
last_name: Sewell
institution: EPFL

non_interactive: true
