{% set name = "activate-aiida" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # created by `python setup.py sdist`
  url: https://github.com/chrisjsewell/activate_aiida/releases/download/{{ version }}/{{ version }}.tar.gz
  # sha256 is the prefered checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge
  #  `conda install openssl -c conda-forge`
  sha256: 6811e1a36086f07f4967e5d7101371eba55cbcecdac6d74ab3dcc63eb4cd4105

build:
  number: 0
  noarch: python
  # skip: True  # [win] # TODO this doesn't work (overriden by noarch)
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - ruamel.yaml
    - jsonschema

test:
  imports:
    - activate_aiida
    - activate_aiida.parse_args
    - activate_aiida.read_config
  commands:
    -   --test
    - source activate-aiida --help

about:
  home: https://github.com/chrisjsewell/activate_aiida
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a package to activate an aiida environment, from a yaml config file
  doc_url: https://github.com/chrisjsewell/activate_aiida
  # dev_url: https://github.com/chrisjsewell/activate_aiida

extra:
  recipe-maintainers:
    - chrisjsewell
